name: Build & Package

on:
  project:
    types: [ closed ]
  pull_request:
    types: [ closed ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Libraries
      run: |
        npm install

    - name: Build
      run: |
        npm run package

    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: |
          sharepoint/solution/page-hacks.sppkg
